### ISSUE TITLE
IllegalModelAccessError in SuppressCheckerResults

### ISSUE THREAD

**Issue by arimer** [mbeddr/mps-qa#200]
Running on MPS 2022.3.2 I see that exception:

```
Failed to initialize part class org.mpsqa.base.errors_suppressor.pluginSolution.plugin.CheckingSuppressorRegistrar_ProjectPluginPart of project plugin class org.mpsqa.base.errors_suppressor.pluginSolution.plugin.PluginSolution_ProjectPlugin

jetbrains.mps.smodel.IllegalModelAccessError: You can read model only inside read actions
	at jetbrains.mps.smodel.AbstractModelAccess.checkReadAccess(AbstractModelAccess.java:67)
	at jetbrains.mps.smodel.ModelAccessBase.checkReadAccess(ModelAccessBase.java:41)
	at jetbrains.mps.extapi.module.SModuleBase.assertCanRead(SModuleBase.java:432)
	at jetbrains.mps.extapi.module.SModuleBase.getModels(SModuleBase.java:155)
	at jetbrains.mps.extapi.module.SModuleBase.getModels(SModuleBase.java:42)
	at jetbrains.mps.ide.findusages.model.scopes.FindUsagesScope.addModule(FindUsagesScope.java:40)
	at jetbrains.mps.ide.findusages.model.scopes.ProjectScope.<init>(ProjectScope.java:15)
	at jetbrains.mps.lang.smodel.query.runtime.CommandUtil.createScope(CommandUtil.java:162)
	at org.mpsqa.base.errors_suppressor.pluginSolution.plugin.SuppressCheckerResults.<init>(SuppressCheckerResults.java:45)
	at org.mpsqa.base.errors_suppressor.pluginSolution.plugin.CheckingSuppressorRegistrar_ProjectPluginPart.init(CheckingSuppressorRegistrar_ProjectPluginPart.java:17)
	at jetbrains.mps.plugins.projectplugins.BaseProjectPlugin.initCustomParts(BaseProjectPlugin.java:74)
	at jetbrains.mps.plugins.projectplugins.BaseProjectPlugin.init(BaseProjectPlugin.java:94)
	at jetbrains.mps.plugins.projectplugins.ProjectPluginManager.createPlugin(ProjectPluginManager.java:159)
	at jetbrains.mps.plugins.projectplugins.ProjectPluginManager.createPlugin(ProjectPluginManager.java:54)
	at jetbrains.mps.plugins.BasePluginManager.createPluginChecked(BasePluginManager.java:156)
	at jetbrains.mps.plugins.BasePluginManager.createPlugins(BasePluginManager.java:143)
	at jetbrains.mps.plugins.BasePluginManager.loadPlugins(BasePluginManager.java:73)
	at jetbrains.mps.plugins.PluginLoaderRegistry.loadContributors(PluginLoaderRegistry.java:206)
	at jetbrains.mps.plugins.PluginLoaderRegistry$UpdatingTask.addContributors(PluginLoaderRegistry.java:564)
	at jetbrains.mps.plugins.PluginLoaderRegistry$UpdatingTask.update(PluginLoaderRegistry.java:542)
	at jetbrains.mps.plugins.PluginLoaderRegistry$UpdatingTask.lambda$run$1(PluginLoaderRegistry.java:452)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:97)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by alexanderpann** [comment]
I feel like this issue was fixed in a later MPS version.
